# Coordinator - tells DOcker how to run multple containers at the same time and how to talk to each other
# Get Kafka running with healthcheck that uses kafka-broker-api-versions.sh

# 3 services -> 3 isolated virtual computers (containers). Each one runs exactly one image.
# Even though they're separate, Docker Compose creates VPN for them - they use Service Names as addresses

services:
  # service 1: actual Broker - long-lived process (server)
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9094:9094" # Dedicated port for your laptop to "listen in"
    networks:
      - tickerpulse-net
    environment:
      # 1. Identity
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "tickerpulse-cluster-id"
      
      # networking: 9092 for internal Docker traffic, 9094 for your laptop
      # internal (9092) - private - Producer and Worker containers live inside the same Docker building, so they use this door. THey look for service named kafka
      # external (9094) - public entrance - Mac is sitting outside Docker building, so we cannot see kafka:9092 address. We need door mapped to localhost:9094 to peek inside
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_data:/var/lib/kafka/data

  # service 2: setup assistant - short-lived task - once it finishes creating topic, it exits with status 0 
  init-kafka:
    image: apache/kafka:latest
    networks:
      - tickerpulse-net
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    # Partitions - parallelism -> can have 3 diff Worker containers running at the same time
    #   Kafka gives each Worker its own partition. Kafka guarantees msg within the same partition stay in order
    # Replications - how many copies 
    command: |
      "
      # This container waits for Kafka, creates the topic, then turns itself off.
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list | grep -q 'ticker_prices' || \
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --topic ticker_prices --partitions 3 --replication-factor 1
      "

  # service 3
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    networks: # private hallway - when we add this to service, we are placing container to specific isolated room
      - tickerpulse-net
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
  
  # service 4
  worker:
    build:
      # Docker zips up the folder and sends it to Docker engine to build container
      context: . # point to the ROOT of project
      dockerfile: worker/Dockerfile
    networks:
      - tickerpulse-net 
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    env_file: 
      - .env
    depends_on:
      kafka:
        condition: service_healthy

# Create the `driver: bridge` virtual software switch (bridge) that connects all containers together while giving them
# a way to talk to outside internet to download updates or hit massive API
networks:
  tickerpulse-net:
    driver: bridge

# Docker creates virtual HD called `kafka_data` 
volumes:
  kafka_data: 